name: Release KursoedovVPN

on:
push:
branches: ["master"]
workflow_dispatch:

jobs:
test:
runs-on: windows-latest
steps:
- uses: actions/checkout@v4
- uses: actions/setup-dotnet@v4
with:
dotnet-version: "8.0.x"
- name: Find solution
shell: pwsh
run: Get-ChildItem -Recurse -Filter "*.sln"
